### ISSUE TITLE
Replace xblock.fragment with web_fragments

### ISSUE THREAD

**Issue by KristinAoki** [open-craft/xblock-vectordraw#22]
As of [2024-02-26](https://docs.openedx.org/projects/xblock/en/latest/changelog.html#id2), `xblock.fragment` has been removed. It has been deprecated since 2018. If courses use this xblock with the newest version of `edx-platform` the course will not be able to load.

Please update vectordraw.py  [L12](https://github.com/open-craft/xblock-vectordraw/blob/0b931ae5d6314dbda5b58ab6c865aea1bc121267/vectordraw/vectordraw.py#L12)

**Comment by bradenmacdonald** [comment]
@KristinAoki Do you know if edx.org has courses that use this XBlock? We can make that change if people are using it, but I'm not even sure if this is still used. We haven't made any feature changes to it in the past seven years, nor any changes at all in the past three.
