### ISSUE TITLE
Preview Mode does not work

### ISSUE THREAD

**Issue by ChristopherChudzicki** [open-craft/xblock-vectordraw#4]
@antoviaque @dseaton
Clicking [View Live] in Studio seems to work, but clicking [Preview] shows error.

<img width="500" alt="screen shot 2016-02-10 at 10 52 16 am" src="https://cloud.githubusercontent.com/assets/9010790/12952504/add08056-cfe4-11e5-8cf1-b7e550f74948.png">
<img width="500" alt="screen shot 2016-02-10 at 10 52 28 am" src="https://cloud.githubusercontent.com/assets/9010790/12952503/add01b66-cfe4-11e5-93aa-54bc62c59f49.png">

**Comment by bradenmacdonald** [comment]
@ChristopherChudzicki does this only happen when Drag and Drop blocks are present, or does it happen in general?

Are you able to see the error message from the LMS logfile? Or could you add me as an instructor on the course where this is happening? (You can get my email address from the email thread, "VectorDraw XBlock issuees")

**Comment by ChristopherChudzicki** [comment]
@bradenmacdonald I just added you to the course. I don't think it's anything to do with drag-and-drop, the course doesn't have any drag and drop problems.

Here's a link to the problem: https://studio.edge.edx.org/container/block-v1:CAC+CAC103+FOREVER+type@vertical+block@fea075357c164e1ba663e085736e29ac

This problem (in Studio or Live) also exhibits the "undraggable" vector issue.

**Comment by bradenmacdonald** [comment]
@ChristopherChudzicki Sorry, I meant "Vector Draw XBlock", not drag and drop.

Thanks for adding me to the course. I can reproduce the problem quite readily, but I'm not sure of the cause off the top of my head. Will add to the list for investigation.

**Comment by bradenmacdonald** [comment]
@ChristopherChudzicki We investigated this and found that this is not really a bug directly.

What was happening was that another vector drawing problem in a different unit (but part of the same subsection) had a JSON error ("Unfixable Broken Problem"). When the LMS displays a unit it also loads all other units in the same subsection at the same time, and in this case the 500 error from "Unfixable Broken Problem" was causing every unit in the subsection to be inaccessible.
