### ISSUE TITLE
On touch devices, drawing a vector also scrolls

### ISSUE THREAD

**Issue by ChristopherChudzicki** [open-craft/xblock-vectordraw#6]
@bradenmacdonald @dseaton @antoviaque

On touchscreens, drawing a new vector also scrolls.

This does not happen when dragging or repositioning a vector, only when drawing a new vector (i.e., when `drawMode=true`). 

See [example](https://edge.edx.org/courses/course-v1:CAC+CAC103+FOREVER/courseware/c59dac19f92e432d93e3086076cce33c/435199ff55a3480f8dc7caa39645aab8/2?activate_block_id=block-v1%3ACAC%2BCAC103%2BFOREVER%2Btype%40vertical%2Bblock%408c12b4a89da645728dcb7d04b291b3e9)  (note `drawMode` is currently broken for first vector, so need to test on second vector.)

**Comment by itsjeyd** [comment]
@bradenmacdonald I think we fixed this via #12? If so, we should probably close this issue :)

(I know we're not working on Vector Drawing ATM; was cleaning up some old notifications in my inbox when I came across this issue.)

**Comment by ChristopherChudzicki** [comment]
@itsjeyd I know this was fixed in the jsinput version; I do not follow the X-Block version as closely. Was it fixed in X-Block?

**Comment by itsjeyd** [comment]
Thanks for the reply, @ChristopherChudzicki. I had a closer look, and #12 seems to be a straightforward port of https://github.com/open-craft/jsinput-vectordraw/pull/31. So I'm assuming the problem has been fixed for the XBlock version. Closing this issue, but let me know if you have any objections.
