### ISSUE TITLE
Problem icon does not show in sequential status bar, HTML icon instead

### ISSUE THREAD

**Issue by ChristopherChudzicki** [open-craft/xblock-vectordraw#7]
See screenshot below:

<img width="1018" alt="screen shot 2016-03-10 at 7 44 49 pm" src="https://cloud.githubusercontent.com/assets/9010790/13765980/7704e200-ea34-11e5-9070-a45c4e634418.png">

**Comment by bradenmacdonald** [comment]
Note for implementation: this seems to be controlled by implementing the `get_icon_class` method.

**Comment by replaceafill** [comment]
Hello. I just created this [PR](https://github.com/open-craft/xblock-vectordraw/pull/14) to fix this issue. Let me know if any other changes are needed.

**Comment by mtyaka** [comment]
@ChristopherChudzicki Thanks for reporting this! It has been fixed in #14.
